"LR": 2e-3
"NUM_ENVS": 16
"NUM_STEPS": 128
"TOTAL_TIMESTEPS": 2e7
"FC_DIM_SIZE": 128
"GRU_HIDDEN_DIM": 128
"UPDATE_EPOCHS": 4
"NUM_MINIBATCHES": 4
"GAMMA": 0.99
"GAE_LAMBDA": 0.95
"CLIP_EPS": 0.2
"SCALE_CLIP_EPS": False
"ENT_COEF": 0.01
"VF_COEF": 0.5
"MAX_GRAD_NORM": 0.5
"ACTIVATION": "tanh"
"ENV_NAME": "MPE_simple_spread_v3"
"SEED": 1
"NUM_SEEDS": 2
"ENV_KWARGS": {}
"ANNEAL_LR": True

# State Attack parameters 
STATE_ATTACK_ENABLED: false  # Set to false by default
STATE_ATTACK_TYPE: "random"  # random, targeted, strategic
STATE_ATTACK_MAGNITUDE: 1
STATE_ATTACK_PROBABILITY: 1
STATE_ATTACK_TARGETED_AGENTS: null  # null means all agents
STATE_ATTACK_FEATURES: null  # null means all features

# Action Attack parameters
ACTION_ATTACK_ENABLED: true
ACTION_ATTACK_TYPE: "random"  # random, targeted, inversion, adversarial
ACTION_ATTACK_PROBABILITY: 0.5
ACTION_ATTACK_STRENGTH: 1.0
ACTION_ATTACK_TARGETED_AGENTS: null  # null means all agents

RUN_COMPARISON: false  # set to true if you want to run both with and without attack

# WandB Params
"WANDB_MODE": "online"
"ENTITY": ""
"PROJECT": "MPE_MAPPO"